Fix missing header and linker error
This commit is used to fix gcc complaining undefined reference to `sqrt`
, though -lm option is already set.

It appears that it is illegal to link with following command:

```bash
  gcc -lm -o filename *.o
```

Therefore, makefile is rectified to

```bash
  gcc -o filename *.o -lm
```

For the record, clang complies perfectly with both commands.